### ISSUE TITLE
fusesoc with alternate Simulator target will fail with missing test-defines.v

### ISSUE THREAD

**Issue by bergyla** [optimsoc/optimsoc#147]
Im still struggling by figuring out how fusesoc generates the build-tree...

I´m interessted in using fosesoc Sim(ulation) with a simulator target other then Verilator but fusesoc stops thenafter with missing test-defines.v.
Using Standard sim run do not facing this issue...

Unfortunately fusesoc is badly documented, and Im still not aware how to stick into the configuration to find the right locations...

**Comment by imphil** [comment]
This seems to be a problem in the core file shipped with mor1kx. 

However, the problem with simulators other than Verilator is that somehow the memory load and/or the debug interconnect need to be simulated. We had/have uartdpi for this purpose, i.e. a BFM for the UART interface which can then be used to connect the remaining debug software to it. However, nobody has been using it for ages and it would need a bit of cleanup before it works again.

Do you have a specific reason for not using Verilator, or is this a blocking issue for you?

**Comment by imphil** [comment]
@bergyla Do you still face this issue and can provide more information? Otherwise I'll close this issue within a week.
