### ISSUE TITLE
Making OpTiMSoc for VCU108

### ISSUE THREAD

**Issue by SRQ91** [optimsoc/optimsoc#159]
Currently I am compiling for the VCU108 by modifying the build.py and replacing nexysddr with vcu108. This works fine but I am wondering if there is a more refined method already implemented for this?

**Comment by koenenwmn** [comment]
You can call fusesoc directly to build the VCU108 example designs. There are readme files for both examples in the subdirectories in '/examples/fpga/vcu108/' which explain the steps in detail.

**Comment by SRQ91** [comment]
Thank you 👍
