### ISSUE TITLE
Invalid website digital SSL certificate

### ISSUE THREAD

**Issue by lucasandradecb** [optimsoc/optimsoc#181]
Hello,
I am working on some projects using your OptimSoc tool. However yesterday, when trying to access the site (https://optimsoc.org/docs/master/refman/porting.html) I received the 404 message from the browser, in addition to the unsafe site information due to problems with the invalid SSL certificate. When checking by the browser it was renewed on 06/10/2019, but it was not validated. With this, so far the site is inaccessible.
Would it be possible to rehabilitate access to the site?

Thank you very much in advance.

**Comment by wallento** [comment]
Hi, sorry, it is temporarily down. It will return asap.

**Comment by wallento** [comment]
Sorry, forgot to ping you. The issue was fixed, thanks again.
