### ISSUE TITLE
Rename repository from sources to optimsoc

### ISSUE THREAD

**Issue by imphil** [optimsoc/optimsoc#68]
Right now, the optimsoc main repository is only usefully named if the full name optimsoc/sources is considered. However, forking a repository e.g. into the personal namespace makes the name "sources" not descriptive at all. Therefore I propose changing the name from "sources" to "optimsoc".

While changing the repository name is annoying, I don't think it will cause major fallout and the number of users relying on it is reasonably small. GitHub also redirects users in a renamed repository (see https://help.github.com/articles/renaming-a-repository/), so existing clones continue to work.

**Comment by wallento** [comment]
Fine for me and done
