### ISSUE TITLE
Document Linux build for OpTiMSoC

### ISSUE THREAD

**Issue by imphil** [optimsoc/optimsoc#76]
Now that we have a (almost working) build of Linux for OpTiMSoC, we should document the steps how to get such a build. A good place would be the Reference Manual (code is here: https://github.com/optimsoc/optimsoc/tree/master/doc/refman)

@ppenna can you have a stab at that?

**Comment by ppenna** [comment]
A draft tutorial is available here: https://github.com/ppenna/optimsoc/blob/host-tile/doc/refman/linux.rst

**Comment by imphil** [comment]
Thanks. Could you add how a user-space init program can be added and the initrd created and integrated?

**Comment by imphil** [comment]
And then please open a Pull Request.

**Comment by ppenna** [comment]
@imphil Sure

**Comment by imphil** [comment]
It's all documented in the user guide now.
